# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/rosas/onex.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onex
resources:
- ../../base
- ingressroute.yaml
- service_account.yaml
- pod_clusterrole.yaml
- pod_clusterrole_binding.yaml
commonLabels:
  onex.io/app: onex-miner-controller
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: onex-miner-controller
  target:
    kind: Deployment
- path: deployment_patch.yaml
  target:
    kind: Deployment
  options:
    allowNameChange: true
- path: service_patch.yaml
  target:
    kind: Service
  options:
    allowNameChange: true
- path: ingressroute.yaml
  target:
    kind: IngressRoute
  options:
    allowNameChange: true
