apiVersion: v1
kind: Service
metadata:
  # 这里名字不能叫 kafka，否则 kafka pod 会一直 crash
  name: onex-kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30006
