apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  serviceName: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.52
        ports:
        - containerPort: 6831
          name: udp-6831
          protocol: UDP
        - containerPort: 6832
          name: udp-6832
          protocol: UDP
        - containerPort: 5778
          name: "tcp-5778"
        - containerPort: 16686
          name: "tcp-16686"
        - containerPort: 4317
          name: "tcp-4317"
        - containerPort: 4318
          name: "tcp-4318"
        - containerPort: 14250
          name: "tcp-14250"
        - containerPort: 14268
          name: "tcp-14268"
        - containerPort: 14269
          name: "tcp-14269"
        - containerPort: 9411
          name: "tcp-9411"
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
