apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # 在这里定义您的自定义资源的属性
              name:
                type: string
              image:
                type: string
          status:
            type: object
            properties:
              # 在这里定义您的自定义资源的状态
              phase:
                type: string
  scope: Namespaced
  names:
    plural: mycustomresources
    singular: mycustomresource
    kind: MyCustomResource
    shortNames:
    - mcr
