# Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/rosas/onex.
#

apiVersion: minersetcontroller.config.onex.io/v1beta1
kind: MinerSetControllerConfiguration
leaderElection:
  leaderElect: false
metricsBindAddress: 0.0.0.0:${ONEX_MINERSET_CONTROLLER_METRICS_PORT}
healthzBindAddress: 0.0.0.0:${ONEX_MINERSET_CONTROLLER_HEALTHZ_PORT}
parallelism: 32
