# 指定了使用的Kubernetes API版本，这里是v1，表示使用了核心API的v1版本
apiVersion: v1
# 指定了要创建的Kubernetes资源类型，这里是Service，表示要创建一个服务
kind: Service
metadata:
  # 指定了服务名
  name: mariadb
  # 指定了 Service 的标签
  labels:
    app: mariadb
# 指定Service的规格，包括服务类型、选择器、端口等信息
spec:
  # 指定了Service的类型为NodePort，表示将会为该服务在每个节点上分配一个端口，通过该端口可以访问Service
  type: NodePort
  # 指定了用于选择后端Pod的标签
  selector:
    app: mariadb
  # 指定了Service需要暴露的端口信息
  ports:
    # 指定了端口的协议为TCP
    - protocol: TCP
      # 指定了Service监听的端口为3306
      port: 3306
      # 指定了要转发到的后端Pod的端口为3306
      targetPort: 3306
      # 指定了分配给Service的节点端口号为30000，表示可以通过节点的IP地址和该端口号来访问Service
      nodePort: 30000
