# 指定了使用的Kubernetes API版本
apiVersion: apps/v1
# 指定了要创建的Kubernetes资源类型，这里是StatefulSet，表示要创建一个有状态的副本集
kind: StatefulSet
# 包含关于StatefulSet的元数据信息，如名称等
metadata:
  # 指定StatefulSet的名称为mariadb
  name: mariadb
  # 指定了 Statefulset 的标签
  labels:
    app: mariadb
# 指定StatefulSet的规格，包括副本数量、选择器、Pod模板等信息
spec:
  # 指定了要创建的Pod副本数量为1
  replicas: 1
  # 指定了用于选择Pod的标签
  selector:
    matchLabels:
      app: mariadb
  # 指定了Pod关联的Service名称
  serviceName: mariadb
  # 指定了要创建的Pod的模板信息
  template:
    # 指定了Pod的元数据信息，包括标签等
    metadata:
      # 指定了Pod的标签
      labels:
        app: mariadb
    # 指定了Pod的规格，包括容器、端口、存储卷挂载、环境变量等信息
    spec:
      # 指定了Pod中的容器信息
      containers:
      # 指定了容器的名称为mariadb
      - name: mariadb
        # 指定了要使用的镜像为mariadb:11.2.2
        image: mariadb:11.2.2
        # 指定了容器需要暴露的端口
        ports:
        - containerPort: 3306
          name: mariadb
        # 指定了要挂载的存储卷信息
        volumeMounts:
        # 指定了要挂载的存储卷的名称为mariadb-persistent-storage
        - name: mariadb-persistent-storage
          # 指定了存储卷在容器中的挂载路径
          mountPath: /var/lib/mysql
        # 指定了容器的环境变量
        # 密码类的环境变量，为了安全，不能以明文的方式在 YAML 中指定，需要通过 secret 挂载
        envFrom:
          - secretRef:
              name: mariadb
  # 指定了要创建的持久化存储卷模板信息
  volumeClaimTemplates:
  # 指定了存储卷模板的元数据信息
  - metadata:
      # 指定了存储卷模板的名称
      name: mariadb-persistent-storage
    # 指定了存储卷的规格信息，包括访问模式和资源请求等
    spec:
      # 指定了存储卷的访问模式为"ReadWriteOnce"，表示可以被单个节点挂载为读写模式
      # ReadWriteOnce: PV 能以 read-write 模式 mount 到单个节点
      # ReadOnlyMany: PV 能以 read-only 模式 mount 到多个节点
      # ReadWriteMany: PV 能以 read-write 模式 mount 到多个节点
      accessModes: [ "ReadWriteOnce" ]
      # 指定了存储卷的资源请求信息
      resources:
        # 指定了存储卷的请求资源
        requests:
          # 指定了存储卷的容量为1GB
          storage: 1Gi
