apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: NodePort
  selector:
    app: etcd
  ports:
    - protocol: TCP
      name: client
      port: 2379
      targetPort: 2379
      nodePort: 30002
    - protocol: TCP
      name: peer
      port: 2380
      targetPort: 2380
      nodePort: 30003
