apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  serviceName: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        command:
          - "/usr/local/bin/etcd"
          - "--advertise-client-urls"
          - "http://0.0.0.0:2379"
          - "--listen-client-urls"
          - "http://0.0.0.0:2379"
          - "--data-dir"
          - "/etcd-data"
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-persistent-storage
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
